package org.usfirst.frc253.Code2016.subsystems;

import org.usfirst.frc253.Code2016.RobotMap;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class GearFlip extends Subsystem {
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

   
    	
    	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
   

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private Spark flip = RobotMap.gearFlipFlip;


// Put methods for controlling this subsystem
// here. Call these from Commands.

public void initDefaultCommand() {}
    public GearFlip() {
    	super();
    	 Retract();
    	 DeployGear();
    	 
    }

public void Retract() {
	flip.set(-0.65);	
}
public void FullStop() {
	flip.set(0);
}

public void DeployGear() {
	flip.set(0.9);


}
}
